# -*- coding: utf-8 -*-
"""Copy of customer_service_bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F04hlNHD3OALWHtGu3AiVX0siq6y0v0z

Press Ctrl + F9 to play script
"""

def cs_service_bot():
    print("Hello! Welcome to the DNS Cable Company's Service Portal. Are you a new or existing customer?\n[1] New Customer\n[2] Existing Customer")    
    response = input("Please enter the number corresponding to your choice:")
    if response==str(1) or response==1:
      result = new_customer()
    elif response==str(2) or response==2:
      result = existing_customer()
    else:
      result = "Sorry, we didn't understand your selection."
    return result

def existing_customer():
    print("What kind of support do you need?\n[1] Television Support\n[2] Internet Support\n[3] Speak to a support representative. ")    
    response = input("Please enter the number corresponding to your choice:")
    if response==str(1) or response==1:
      result = television_support()
    elif response==str(2) or response==2:
      result = internet_support()
    elif response==str(3) or response==3:
      result = live_rep("support")
    else:
      print("Sorry, we didn't understand your selection.")
      result = existing_customer()
    return result

def new_customer():
    print("We're excited to have you join the DNS family, how can we help you?\n[1] Sign up for service.\n[2] Schedule a home visit.\n[3] Speak to a sales representative.")    
    response = input("Please enter the number corresponding to your choice:")
    if response==str(1) or response==1:
      result = sign_up()
    elif response==str(2) or response==2:
      result = home_visit()
    elif response==str(3) or response==3:
      result = live_rep("sales")
    else:
      print("Sorry, we didn't understand your selection.")
      result = existing_customer()
    return result

def television_support():
  print("What is the nature of your problem?\n[1] I can't access certain channels.\n[2] My picture is blurry.\n[3] I keep losing service.\n[4] Other issues.")
  response = input("Please enter the number corresponding to your choice:")
  if response==str(1) or response==1:
    print("Please check the channel lists at DefinitelyNotSinister.com. If the channel you cannot access is there, please contact a live representative.")
    result = did_that_help()
  elif response==str(2) or response==2:
    print("Try adjusting the antenna above your television set.")
    result = did_that_help()
  elif response==str(3) or response==3:
    print("Is it raining outside? If so, wait until it is not raining and then try again.")
    result = did_that_help()
  elif response==str(4) or response==4:
    result = live_rep("Support")
  else:
    print("Sorry, we didn't understand your selection.")
    result = television_support()
  return result

def internet_support():
  print("What is the nature of your problem?\n[1] I can't connect to the internet.\n[2] My connection is very slow.\n[3] I can't access certain sites.")
  response = input("Please enter the number corresponding to your choice:")
  if response==str(1) or response==1:
    print("Unplug your router, then plug it back in, then give it a good whack, like the Fonz.")
    result = did_that_help()
  elif response==str(2) or response==2:
    print("Make sure that all cell phones and other peoples computers are not connected to the internet, so that you can have all the bandwidth.")
    result = did_that_help()
  elif response==str(3) or response==3:
    print("Move to a different region or install a VPN. Some areas block certain sites.")
    result = did_that_help()
  elif response==str(4) or response==4:
    result = live_rep("Support")
  else:
    print("Sorry, we didn't understand your selection.")
    result = television_support()
  return result

def did_that_help():
  response1 = input("Did that solve the problem? [Yes] or [No]")
  if response1 == "Yes" or input == "yes":
    print("thank you")
  elif response1 =="No" or input == "no":
    response2 = input("Would you like to:\n  [1]Talk to a live representative.\n  [2]Schedule a home visit.")
    if response2==str(1) or response==1:
      result = live_rep("support")
    elif response2==str(2) or response==2:
      result = home_visit("support")
    else:
      print("Sorry, we didn't understand your selection.")
    result = did_that_help
  return result

def sign_up():
  print("Great choice, friend! We're excited to have you join the DNS family! Please select the package you are interested in signing up for.\n [1] Bundle Deal (Internet + Cable)\n [2] Internet\n [3] Cable")
  response = input("Please enter the number corresponding to your choice:")
  if response==str(1) or response==1:
    print(" You've selected the Bundle Package! Please schedule a home visit and our technician will come and set up your new service.")
    result = home_visit("new install")
  elif response==str(2) or response==2:
    print("You've selected the Internet Only Package! Please schedule a home visit and our technician will come and set up your new service.")
    result = home_visit("new install")
  elif response==str(3) or response==3:
    print("You've selected the Cable Only Package! Please schedule a home visit and our technician will come and set up your new service.")
    result = home_visit("new install")
  else:
    print("Sorry, we didn't understand your selection.")
    result = sign_up()
  return result

def home_visit(purpose="none"):
  if purpose == "none":
    result1 = input("What is the purpose of the home visit you need?\n[1] New service installation.\n[2] Exisitng service repair.\n[3] Location scouting for unserviced region.\n")
    if result1==str(1) or result1==1:
      purpose = "new install"
      return home_visit(purpose)
    elif result1==str(2) or result1==2:
      purpose = "support"
      return home_visit(purpose)
    elif result1==str(3) or result1==3:
      purpose = "scout"
      return home_visit(purpose)
    else:
      print("Sorry, we didn't understand your selection.")
      result2 = home_visit()
  else:
    visit_date = input("Please enter a date below when you are available for a technician to come to your home and " + purpose + ".")
    print("Wonderful! A technical will come visit you on" + visit_date +". Please be available between the hours of 1:00 am and 11:00 pm.")
  result2 = visit_date
  return result2

def live_rep(purpose):
  if purpose == "sales":
    print("Please hold while we connect you with a live sales representative. The wait time will be between two minutes and six hours. We thank you for your patience.")
  else:
    print("Please hold while we connect you with a live support representative. The wait time will be between two minutes and six hours. We thank you for your patience.")

cs_service_bot()